### ISSUE TITLE
Mono-Z sensitivity: edited

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#10]
Hi @cranelli, @AndreasAlbert, 

I've had a go at editing the sensitivity part for the mono-Z in the pdf / tex. The files are here:

https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/DMWG-2HDM-whitepaper_Main.pdf

and 

https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/texinputs/04_grid/SensitivityStudies.tex

Could you have a look if there's anything missing? 

One doubt I have is the mono-Z (had) that seems to have a much worse sensitivity than the leptonic search - to the point that it never approaches the chosen value of 2 anywhere in the two planes that we show. I've emailed Koji (he's not on git) to find out more, but if you have discussed it in internal meetings I'd be happy to hear the reasoning and add a sentence. 

Thanks,
Caterina

**Comment by AndreasAlbert** [comment]
Hi @urania277, did Koji get back to you? If not, I will open a common email thread to resolve this. It is not immediately obvious to me why the sensitivity is that low.

Regarding the document: The selection tables seem to have dropped out of the appendix, but you are probably aware of that.

**Comment by caterina-doglioni** [comment]
Hi @AndreasAlbert, 

I'm back to this after the exams for my course so sorry for the temporary silence, the theory and ID part are also converging (committing work from Uli and Linda today) so everything is getting there. 

Thanks for having a look - in the last version the appendix had dropped out entirely as I wanted to keep things more lightweight for those reading. 

I had no answer yet from Koji, but I had some exchange with @obrandt1 - he said this was studied internally and they found out that some of the assumptions made for the sensitivity were too conservative, possibly the ones on the background. At this stage there is no time (or people) to redo the study, so I think we will only show mono-Z(lep) and mono-H for the sensitivity, but leave the kinematic plots as example of the interplay of resolved and boosted signatures. 

I will make another issue for the overall experimental part and send it around via mail as well. 

Caterina
