### ISSUE TITLE
ATLAS work in progress to be removed from ttbar res figures

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#12]
Dear @Awen0121, 

Could you please remove the "ATLAS Work in progress" label from those plots?

https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/tree/DMWG_edited/texinputs/04_grid/figures/ttres

Thanks,
Caterina

**Comment by Awen0121** [comment]
Dear @urania277,

I uploaded the version without "work in progress" label to master branch very long ago. What am I supposed to do now? update the plots in "DMWG_edited" as well? 

Thanks,
Yu-Heng

**Comment by caterina-doglioni** [comment]
Sorry I never answered, but the plots have made it in the new versions, thanks! Closing this issue.
