### ISSUE TITLE
Mislabeling found by Chris Anelli

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#6]
I was quickly looking at the White Paper again.  I believe there is a mislabel on Figure 64.  Should be 2mDM =mA.

**Comment by caterina-doglioni** [comment]
Assigning this to @AndreasAlbert as this is one of the two relic density figures here: ![screen shot 2018-04-29 at 22 02 31](https://user-images.githubusercontent.com/8102713/39410469-fc8e8f48-4bf8-11e8-9c0d-fede88430ece.png)

**Comment by AndreasAlbert** [comment]
Thanks for catching this @cranelli @urania277 !

Fixed in a8527d695e01c62c6903aabd2d99213352be29a6

**Comment by caterina-doglioni** [comment]
Thanks both! closing.
