### ISSUE TITLE
Mono-H plots: clarification on color scheme

### ISSUE THREAD

**Issue by caterina-doglioni** [LHC-DMWG/DMWG-2HDM-whitepaper#9]
Hi @lhenkelm, @obrandt1, 
an easy question: the white areas in the significance figures correspond to points that we haven't generated rather than off-scale sensitivity, right? If so I will modify the caption to make it clearer. 
Thanks,
Caterina

**Comment by lhenkelm** [comment]
Hi  @urania277 ,

Thanks for noticing that! Its actually the other way around (so its good to clarify in the caption): white is off-scale (i.e. below 0.1). We have points generated evenly, everywhere (as the [xsec plots in the appendix](https://github.com/LHC-DMWG/DMWG-2HDM-whitepaper/blob/DMWG_edited/texinputs/04_grid/figures/monoHbb_parton_level_cross_section_bin_1_ma_vs_mA_lin.pdf) show). When editing the caption, note that for points that are off-scale in the other direction (i.e. >> 1), we instead show them in the color associated with the uppermost color bin.

Cheers, 
Lars
